
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_BY_NAME = "GET_BY_NAME";
export const ADD_ACTIVITIES = "ADD_ACTIVITIES";
export const COUNTRY_DETAIL = "COUNTRY_DETAIL";
export const CLEAN_DETAIL = "CLEAN_DETAIL";
export const SET_CURRENT_PAGE = "SET_CURRENT_PAGE";
export const FILTER_COUNTRY_CONTINENT = "FILTER_COUNTRY_CONTINENT";
export const FILTER_ACTIVITIES = "FILTER_ACTIVITIES";
export const ORDER = "ORDER";
export const GET_ACTIVITIES = "GET_ACTIVITIES";
export const COUNTRY_ACTIVITIES = "COUNTRY_ACTIVITIES";
